# Pipeline DVC para el proyecto PLS

stages:
  preprocess:
    cmd: python src/data/make_dataset.py
    deps:
      - src/data/make_dataset.py
      - data/raw
    params:
      - data
    outs:
      - data/processed/dataset_clean.csv
      - data/processed/dataset_clean.jsonl
      - data/processed/dataset_clean_stats.json

  split:
    cmd: python src/data/split_dataset.py
    deps:
      - src/data/split_dataset.py
      - data/processed/dataset_clean.csv
    params:
      - split
    outs:
      - data/processed/train.csv
      - data/processed/test.csv


