"""
Cliente de ejemplo para la API de PLS
Muestra cómo interactuar con la API desde Python
"""

import requests
import json
from typing import Dict, Optional

class PLSClient:
    """Cliente para interactuar con la API de PLS"""
    
    def __init__(self, base_url: str = "http://localhost:8000"):
        self.base_url = base_url
        self.session = requests.Session()
    
    def health_check(self) -> Dict:
        """Verifica el estado de la API"""
        response = self.session.get(f"{self.base_url}/health")
        response.raise_for_status()
        return response.json()
    
    def generar_pls(
        self,
        technical_text: str,
        max_length: int = 256,
        num_beams: int = 4
    ) -> Dict:
        """
        Generates a PLS from technical text
        
        Args:
            technical_text: Medical technical text to simplify
            max_length: Maximum output length
            num_beams: Number of beams for generation
        
        Returns:
            Dict with generated_pls, generation_time, etc.
        """
        response = self.session.post(
            f"{self.base_url}/generate",
            json={
                "technical_text": technical_text,
                "max_length": max_length,
                "num_beams": num_beams
            }
        )
        response.raise_for_status()
        return response.json()
    
    def evaluar_pls(
        self,
        original_text: str,
        generated_pls: str,
        reference_pls: Optional[str] = None
    ) -> Dict:
        """
        Calculates metrics for a PLS
        
        Args:
            original_text: Original technical text
            generated_pls: PLS generated by the model
            reference_pls: Reference PLS (optional)
        
        Returns:
            Dict with all metrics
        """
        payload = {
            "original_text": original_text,
            "generated_pls": generated_pls
        }
        if reference_pls:
            payload["reference_pls"] = reference_pls
        
        response = self.session.post(
            f"{self.base_url}/evaluate",
            json=payload
        )
        response.raise_for_status()
        return response.json()
    
    def generar_con_metricas(
        self,
        technical_text: str,
        reference_pls: Optional[str] = None,
        max_length: int = 256,
        num_beams: int = 4
    ) -> Dict:
        """
        Generates PLS and calculates metrics in a single request
        
        Args:
            technical_text: Medical technical text
            reference_pls: Reference PLS (optional)
            max_length: Maximum output length
            num_beams: Number of beams
        
        Returns:
            Dict with generated_pls and metrics
        """
        payload = {
            "technical_text": technical_text,
            "max_length": max_length,
            "num_beams": num_beams
        }
        if reference_pls:
            payload["reference_pls"] = reference_pls
        
        response = self.session.post(
            f"{self.base_url}/generate-with-metrics",
            json=payload
        )
        response.raise_for_status()
        return response.json()

# ============================================================================
# EJEMPLOS DE USO
# ============================================================================

def ejemplo_basico():
    """Ejemplo básico de generación de PLS"""
    print("="*80)
    print("EJEMPLO 1: Generación Básica de PLS")
    print("="*80)
    
    # Crear cliente
    client = PLSClient()
    
    # Verificar que la API está funcionando
    health = client.health_check()
    print(f"✅ API Status: {health['status']}")
    print(f"   Model loaded: {health['model_loaded']}")
    print(f"   Device: {health['device']}")
    print()
    
    # Texto técnico de ejemplo
    texto = """
    Systemic arterial hypertension is a chronic medical condition characterized 
    by persistent elevation of blood pressure in the arteries. It is defined 
    as a systolic blood pressure equal to or greater than 140 mmHg and/or a 
    diastolic blood pressure equal to or greater than 90 mmHg in multiple measurements. 
    This condition can lead to serious cardiovascular complications if not treated 
    properly, including stroke, myocardial infarction, congestive heart failure, 
    chronic kidney disease and hypertensive retinopathy.
    """
    
    print("📝 Technical text:")
    print(texto.strip()[:200] + "...")
    print()
    
    # Generar PLS
    print("🔄 Generating PLS...")
    resultado = client.generar_pls(texto)
    
    print(f"\n✅ Generated PLS:")
    print(f"{resultado['generated_pls']}")
    print()
    print(f"⏱️  Time: {resultado['generation_time']:.3f}s")
    print(f"📊 Chunks: {resultado['num_chunks']}")
    print(f"🔢 Tokens input: {resultado['tokens_input']}")
    print(f"🔢 Tokens output: {resultado['tokens_output']}")
    print()

def ejemplo_con_metricas():
    """Ejemplo con cálculo de métricas"""
    print("="*80)
    print("EJEMPLO 2: Generación + Métricas")
    print("="*80)
    
    client = PLSClient()
    
    texto = """
    Metabolic syndrome is a set of conditions that include abdominal obesity, 
    insulin resistance, arterial hypertension and dyslipidemia, which significantly 
    increase the risk of developing type 2 diabetes mellitus and cardiovascular disease.
    """
    
    # Reference PLS (optional)
    pls_ref = """
    Metabolic syndrome is a group of health problems that include excess fat in 
    the abdomen, difficulty using insulin, high blood pressure and abnormal cholesterol 
    levels. These problems together greatly increase the risk of having type 2 diabetes 
    and heart disease.
    """
    
    print("🔄 Generating PLS with metrics...")
    resultado = client.generar_con_metricas(
        technical_text=texto,
        reference_pls=pls_ref
    )
    
    print(f"\n✅ Generated PLS:")
    print(f"{resultado['generated_pls']}")
    print()
    
    print("📊 METRICS:")
    print("-" * 80)
    metricas = resultado['metrics']
    
    # Similarity metrics
    print("\n🔍 Similarity/Overlap:")
    if metricas.get('rouge1'):
        print(f"  ROUGE-1:     {metricas['rouge1']:.3f}")
        print(f"  ROUGE-2:     {metricas['rouge2']:.3f}")
        print(f"  ROUGE-L:     {metricas['rougeL']:.3f}")
        print(f"  BLEU:        {metricas['bleu']:.3f}")
        print(f"  METEOR:      {metricas['meteor']:.3f}")
        if metricas.get('bertscore_f1'):
            print(f"  BERTScore:   {metricas['bertscore_f1']:.3f}")
    
    # Simplification
    print("\n📝 Simplification:")
    if metricas.get('sari'):
        print(f"  SARI ⭐:     {metricas['sari']:.3f}  ", end="")
        if metricas['sari'] >= 0.40:
            print("(✅ Good)")
        else:
            print("(⚠️  Needs improvement)")
    
    # Readability
    print("\n📖 Readability:")
    print(f"  Flesch RE:   {metricas['flesch_reading_ease']:.1f}  ", end="")
    if 60 <= metricas['flesch_reading_ease'] <= 70:
        print("(✅ 8th grade level)")
    else:
        print(f"(Target: ~64)")
    
    print(f"  Flesch KG:   {metricas['flesch_kincaid_grade']:.1f}  ", end="")
    if 6 <= metricas['flesch_kincaid_grade'] <= 9:
        print("(✅ 8th grade level)")
    else:
        print(f"(Target: ~7.4)")
    
    # Compression
    print("\n📉 Compression:")
    print(f"  Ratio:       {metricas['compression_ratio']:.2f}  ", end="")
    if 0.30 <= metricas['compression_ratio'] <= 0.40:
        print("(✅ Optimal)")
    else:
        print(f"(Target: 0.33-0.37)")
    
    print(f"  Length:      {metricas['word_length']} words")
    print(f"  Original:    {metricas['original_word_length']} words")
    
    print()
    print(f"⏱️  Total time: {resultado['generation_time']:.3f}s")
    print()

def ejemplo_batch():
    """Ejemplo procesando múltiples textos"""
    print("="*80)
    print("EJEMPLO 3: Procesamiento Batch")
    print("="*80)
    
    client = PLSClient()
    
    textos = [
        "Type 2 diabetes mellitus is a metabolic disease characterized by chronic hyperglycemia.",
        "Osteoporosis is a systemic bone disease characterized by decreased bone mineral density.",
        "Bronchial asthma is a chronic inflammatory disease of the airways."
    ]
    
    print(f"📋 Processing {len(textos)} texts...\n")
    
    for i, texto in enumerate(textos, 1):
        print(f"Text {i}:")
        print(f"  Input:  {texto[:60]}...")
        
        resultado = client.generar_pls(texto)
        
        print(f"  Output: {resultado['generated_pls'][:60]}...")
        print(f"  Time: {resultado['generation_time']:.3f}s")
        print()

# ============================================================================
# MAIN
# ============================================================================

if __name__ == "__main__":
    try:
        # Ejecutar ejemplos
        ejemplo_basico()
        print("\n" + "="*80 + "\n")
        
        ejemplo_con_metricas()
        print("\n" + "="*80 + "\n")
        
        ejemplo_batch()
        
        print("✅ All examples completed successfully")
        
    except requests.exceptions.ConnectionError:
        print("❌ Error: Could not connect to the API")
        print("   Make sure the API is running at http://localhost:8000")
        print("   Run: python main.py")
    except Exception as e:
        print(f"❌ Error: {e}")
        import traceback
        traceback.print_exc()

